# Generated by Django 5.0.6 on 2024-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_trip_image_tripimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
