# Generated by Django 5.0.6 on 2024-06-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_trip_image_alter_trip_id_tripimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
